#ifndef __MESSAGE_TAG_H
#define __MESSAGE_TAG_H 1

#define SEND_DENSE_MATRIX_DIMENSION 0
#define SEND_DENSE_MATRIX_CONTENT 1
#define SEND_PROCESS_LIST_N_PROC 2
#define SEND_PROCESS_LIST_PROCESSES 2

#endif